
SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";



CREATE TABLE IF NOT EXISTS CUSTOMER(
 C_ID INT AUTO_INCREMENT,
 CUST_NAME VARCHAR(20) NOT NULL,
 PH_NO NUMBER(10) NOT NULL,
 EMAIL_ID VARCHAR(255) NOT NULL,
 PASSWORD VARCHAR(12) NOT NULL,
 CONSTRAINT PK_CID PRIMARY KEY(C_ID);
)

CREATE TABLE IF NOT EXISTS ADMIN(
 A_ID INT AUTO AUTO_INCREMENT,
 ADMIN_NAME VARCHAR(20) NOT NULL,
 A_PH NUMBER(10) NOT NULL,
 PASSWORD VARCHAR(12) NOT NULL,
 CONSTRAINT PK_AID PRIMARY KEY(A_ID);
)

CREATE TABLE IF NOT EXITS MENU(
	ITEM_NAME VARCHAR(20) NOT NULL,
	ITEM_ID 
	ITEM_COST 
)

CREATE TABLE IF NOT EXISTS ORDERS(
	ORDER_NO 
	CUST_ID
	TOTAL_PRICE
)

